// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Fizzbuzz struct {
	ID        int64     `json:"id"`
	Useragent string    `json:"useragent"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}
