// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFizzBuzz(ctx context.Context, arg CreateFizzBuzzParams) (sql.Result, error)
	GetFizzBuzz(ctx context.Context, id int64) (Fizzbuzz, error)
	ListFizzBuzzes(ctx context.Context) ([]Fizzbuzz, error)
}

var _ Querier = (*Queries)(nil)
